# Generated by Django 5.2.1 on 2025-05-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MNO', models.CharField(max_length=100)),
                ('Code', models.CharField()),
                ('Latitude', models.FloatField(max_length=100)),
                ('Longitude', models.FloatField(max_length=50)),
            ],
            options={
                'verbose_name': 'Telefonica',
                'verbose_name_plural': 'Telefonica',
            },
        ),
    ]
