# Generated by Django 5.2.1 on 2025-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefonica',
            options={'verbose_name': 'Telefonica Tower', 'verbose_name_plural': 'Telefonica Towers'},
        ),
        migrations.AlterField(
            model_name='telefonica',
            name='Code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='telefonica',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='telefonica',
            name='Longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='telefonica',
            name='MNO',
            field=models.CharField(max_length=100, verbose_name='Mobile Network Operator'),
        ),
    ]
