# Generated by Django 5.2.1 on 2025-05-10 10:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0002_alter_telefonica_options_alter_telefonica_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonica',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='telefonica',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='telefonica',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
