# Generated by Django 5.2.1 on 2025-05-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0003_remove_telefonica_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonica',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefonica',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
