# Generated by Django 5.2.1 on 2025-05-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0004_telefonica_latitude_telefonica_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefonica',
        ),
    ]
