# Generated by Django 5.2.1 on 2025-05-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teleapp', '0005_delete_telefonica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mno', models.CharField(max_length=50, verbose_name='Mobile Network Operator')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['mno', 'code'],
            },
        ),
    ]
