# Generated by Django 5.2.1 on 2025-05-11 18:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mno', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Telefonica',
        ),
    ]
